# .github/workflows/convert-to-pdf.yml

name: Docs to PDF

on:
  push:
    branches:
      - main
    paths:
      - '*.md'               # Überwacht Änderungen an .md-Dateien im Root-Verzeichnis
      - 'images/**'          # Überwacht Änderungen an Dateien in allen Unterverzeichnissen von /images

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: '20'  # Nutze Node.js 20

      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: .            # Root-Verzeichnis als Eingabeverzeichnis (wo deine .md-Dateien liegen)
          output_dir: pdfs         # Ausgabeverzeichnis für die PDFs
          images_dir: images       # Verzeichnis, in dem die Bilder liegen (images/documentation, images/example)
          image_import: ./images   # Pfad für Bilder in den Markdown-Dateien
          build_html: false        # Nur PDF-Dateien generieren

      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: pdfs               # Hochladen der PDFs als Artefakt