# .github/workflows/convert-to-pdf.yml

name: Docs to PDF

on:
  push:
    branches:
      - main
    paths:
      - '*.md'
      - 'images/**'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3      # Setzt die Node.js-Version
        with:
          node-version: '20'             # Node.js 20 verwenden

      - uses: actions/checkout@v3        # Checkt das Repository aus

      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: .
          output_dir: pdfs
          images_dir: images
          image_import: ./images
          build_html: false

      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: pdfs                     # Hochladen der generierten PDFs
